import type { AnalystData, EnergyData, InsightData, IntradayData, MarketData, NewsData, PortfolioConfig } from "../types";

// All data files are static JSON regenerated by the scheduled fetch
// pipeline and deployed alongside the built site — see data/fetch/.
const BASE = `${import.meta.env.BASE_URL}data`;

async function loadJson<T>(path: string): Promise<T | null> {
  try {
    const res = await fetch(path, { cache: "no-store" });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

export function loadMarketData(ticker: string) {
  return loadJson<MarketData>(`${BASE}/${ticker}/market.json`);
}

export function loadIntradayData(ticker: string) {
  return loadJson<IntradayData>(`${BASE}/${ticker}/intraday.json`);
}

export function loadEnergyData(ticker: string) {
  return loadJson<EnergyData>(`${BASE}/${ticker}/energy.json`);
}

export function loadNewsData(ticker: string) {
  return loadJson<NewsData>(`${BASE}/${ticker}/news.json`);
}

export function loadAnalystData(ticker: string) {
  return loadJson<AnalystData>(`${BASE}/${ticker}/analyst.json`);
}

export function loadInsightData(ticker: string) {
  return loadJson<InsightData>(`${BASE}/${ticker}/insight.json`);
}

// Portfolio share count is real financial data and this repo is public,
// so it's never committed to git — persisted server-side instead, via
// gate.php's /api/portfolio endpoint (see public/gate.php), so both
// household members see the same value from any device. In local dev
// (no PHP server) this 404s and loadJson returns null, same as any
// other missing data file — the UI falls back to its empty state.
const PORTFOLIO_API = `${import.meta.env.BASE_URL}api/portfolio`;

export function loadPortfolioConfig() {
  return loadJson<PortfolioConfig>(PORTFOLIO_API);
}

export async function savePortfolioConfig(shares: number | null): Promise<PortfolioConfig | null> {
  try {
    const res = await fetch(PORTFOLIO_API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ shares }),
    });
    if (!res.ok) return null;
    return (await res.json()) as PortfolioConfig;
  } catch {
    return null;
  }
}
