import type { AnalystData, EnergyData, MarketData, NewsData, PortfolioConfig } from "../types";

// All data files are static JSON regenerated by the scheduled fetch
// pipeline and deployed alongside the built site — see data/fetch/.
const BASE = `${import.meta.env.BASE_URL}data`;

async function loadJson<T>(path: string): Promise<T | null> {
  try {
    const res = await fetch(path, { cache: "no-store" });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

export function loadMarketData(ticker: string) {
  return loadJson<MarketData>(`${BASE}/${ticker}/market.json`);
}

export function loadEnergyData(ticker: string) {
  return loadJson<EnergyData>(`${BASE}/${ticker}/energy.json`);
}

export function loadNewsData(ticker: string) {
  return loadJson<NewsData>(`${BASE}/${ticker}/news.json`);
}

export function loadAnalystData(ticker: string) {
  return loadJson<AnalystData>(`${BASE}/${ticker}/analyst.json`);
}

// Portfolio config is intentionally never committed to the (public) repo —
// see src/config/portfolio.example.json. It's fetched at runtime and
// simply absent (404) unless the user has placed their own copy at
// public/portfolio.json locally.
export function loadPortfolioConfig() {
  return loadJson<PortfolioConfig>(`${import.meta.env.BASE_URL}portfolio.json`);
}
