import type { AnalystData, CrackSpreadData, DividendData, EnergyData, InsiderData, InsightData, IntradayData, MarketData, NewsData, PortfolioConfig, RSIData, VolumeData } from "../types";

// All data files are static JSON regenerated by the scheduled fetch
// pipeline and deployed alongside the built site — see data/fetch/.
const BASE = `${import.meta.env.BASE_URL}data`;

async function loadJson<T>(path: string): Promise<T | null> {
  try {
    const res = await fetch(path, { cache: "no-store" });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

export function loadMarketData(ticker: string) {
  return loadJson<MarketData>(`${BASE}/${ticker}/market.json`);
}

export function loadIntradayData(ticker: string) {
  return loadJson<IntradayData>(`${BASE}/${ticker}/intraday.json`);
}

export function loadEnergyData(ticker: string) {
  return loadJson<EnergyData>(`${BASE}/${ticker}/energy.json`);
}

export function loadNewsData(ticker: string) {
  return loadJson<NewsData>(`${BASE}/${ticker}/news.json`);
}

export function loadAnalystData(ticker: string) {
  return loadJson<AnalystData>(`${BASE}/${ticker}/analyst.json`);
}

export function loadRSIData(ticker: string) {
  return loadJson<RSIData>(`${BASE}/${ticker}/rsi.json`);
}

export function loadCrackSpreadData(ticker: string) {
  return loadJson<CrackSpreadData>(`${BASE}/${ticker}/crack_spread.json`);
}

export function loadInsiderData(ticker: string) {
  return loadJson<InsiderData>(`${BASE}/${ticker}/insider.json`);
}

export function loadVolumeData(ticker: string) {
  return loadJson<VolumeData>(`${BASE}/${ticker}/volume.json`);
}

export function loadDividendData(ticker: string) {
  return loadJson<DividendData>(`${BASE}/${ticker}/dividends.json`);
}

export function loadInsightData(ticker: string) {
  return loadJson<InsightData>(`${BASE}/${ticker}/insight.json`);
}

// Portfolio share count is real financial data and this repo is public,
// so it's never committed to git — persisted server-side instead, via
// gate.php's /api/portfolio endpoint (see public/gate.php), keyed by
// ticker so each holding (MPC, COP, ...) has its own share count. Both
// household members see the same value from any device. In local dev
// (no PHP server) this 404s and loadJson returns null, same as any
// other missing data file — the UI falls back to its empty state.
const PORTFOLIO_API = `${import.meta.env.BASE_URL}api/portfolio`;

export function loadPortfolioConfig(ticker: string) {
  return loadJson<PortfolioConfig>(`${PORTFOLIO_API}?ticker=${ticker}`);
}

export async function savePortfolioConfig(ticker: string, shares: number | null): Promise<PortfolioConfig | null> {
  try {
    const res = await fetch(`${PORTFOLIO_API}?ticker=${ticker}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ shares }),
    });
    if (!res.ok) return null;
    return (await res.json()) as PortfolioConfig;
  } catch {
    return null;
  }
}
