<?php
// Local CLI tool: writes NBHS86/config.local.php (gitignored, not deployed).
//   php tools/make-config.php --passcode=NBHS86 [--admin-password=...] [--data-dir=/path] [--out=/path/config.local.php]
// If --admin-password is omitted a random one is generated and printed once.
// Reuses the existing secret in --out if present so cookies stay valid across regenerations.

if (PHP_SAPI !== 'cli') {
    exit(1);
}
$opt = [];
foreach (array_slice($argv, 1) as $a) {
    if (preg_match('/^--([a-z-]+)=(.*)$/s', $a, $m)) {
        $opt[$m[1]] = $m[2];
    }
}
// CI mode: `--from-env` reads NBHS86_PASSCODE / NBHS86_ADMIN_PASSWORD / NBHS86_SECRET (GitHub secrets)
// and prints nothing secret. All three are required so the cookie secret stays stable across deploys.
$fromEnv = in_array('--from-env', $argv, true);
if ($fromEnv) {
    $opt['passcode'] = (string) getenv('NBHS86_PASSCODE');
    $opt['admin-password'] = (string) getenv('NBHS86_ADMIN_PASSWORD');
    $opt['secret'] = (string) getenv('NBHS86_SECRET');
    if ($opt['passcode'] === '' || $opt['admin-password'] === '' || strlen($opt['secret']) < 32) {
        fwrite(STDERR, "--from-env needs NBHS86_PASSCODE, NBHS86_ADMIN_PASSWORD and NBHS86_SECRET (32+ chars).\n");
        exit(1);
    }
}
$passcode = $opt['passcode'] ?? null;
if ($passcode === null || $passcode === '') {
    fwrite(STDERR, "Usage: php tools/make-config.php --passcode=WORD [--admin-password=PW] [--data-dir=DIR] [--out=FILE] | --from-env\n");
    exit(1);
}
$out = $opt['out'] ?? dirname(__DIR__) . '/config.local.php';
$adminPw = $opt['admin-password'] ?? bin2hex(random_bytes(9));
$generated = !isset($opt['admin-password']);

$secret = $opt['secret'] ?? null;
if ($secret === null && is_file($out)) {
    $prev = require $out;
    $secret = is_array($prev) ? ($prev['secret'] ?? null) : null;
}
$secret ??= bin2hex(random_bytes(32));

$cfg = [
    'passcode_hash' => password_hash(strtolower(preg_replace('/\s+/', '', $passcode)), PASSWORD_BCRYPT),
    'admin_hash' => password_hash($adminPw, PASSWORD_BCRYPT),
    'secret' => $secret,
];
if (!empty($opt['data-dir'])) {
    $cfg['data_dir'] = $opt['data-dir'];
}
file_put_contents($out, "<?php\n// Generated by tools/make-config.php. Never commit. Not deployed by CI.\nreturn " . var_export($cfg, true) . ";\n");
chmod($out, 0600);
echo $fromEnv ? "Wrote config.local.php from environment\n" : "Wrote $out\n";
if ($generated) {
    echo "Admin password (shown once): $adminPw\n";
}
